export type AboutConfig = typeof aboutConfig

export const aboutConfig = {
  title: "Hello! I'm Sebastian Rodriguez, recent university graduate and gym enthusiast",
  introduction: "Hello there! My name is Sebastian Rodriguez, and I am thrilled to introduce myself as an aspiring computer science engineer. With a recent graduation under my belt, I am now eagerly seeking opportunities to expand my knowledge, skills, and expertise in this ever-evolving field.",
  education: "I hold a Bachelor's degree in Computer Science, a testament to my dedication and passion for the subject. To stay ahead of the game, I am currently pursuing certifications in React, Next, and AWS, as I believe in the importance of continuous learning and growth. My technical prowess encompasses TypeScript, Node.js, React, Express, and a variety of other programming languages, software development tools, databases, algorithms, and frameworks.",
  experience: "Throughout my academic journey, I actively engaged in internships, freelance work, and personal projects that allowed me to put my skills into practice and gain hands-on experience. One notable endeavor involved building a cutting-edge web application using React and Node.js. My responsibilities primarily focused on front-end development and seamless API integration, resulting in a highly functional and visually appealing application.",
  collaboration: "Collaboration has played a pivotal role in my growth as a computer science engineer. Through various projects, including website development, chatbot implementation, and game design, I have had the opportunity to work closely with diverse teams. Effective communication and seamless coordination were essential in harnessing each team member's strengths and creating synergistic outcomes. I have learned the invaluable art of teamwork, understanding that open dialogue and collective effort drive success.",
  personal: "Beyond the realm of computer science, I am an ardent painter, using my artistic pursuits to foster creativity and balance in my life. I firmly believe that maintaining a healthy work-life equilibrium is vital for long-term success and overall well-being. In line with this philosophy, I regularly engage in workouts and physical activities, which rejuvenate my mind and body, keeping me energized and focused."
}
